dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install beautifulsoup4
  - pip install --only-binary=numpy,pandas numpy pandas
# command to run tests
script:
  - python -m pytest
