language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install beautifulsoup4 pytest pytest-cov
  - pip install --only-binary=numpy,pandas numpy pandas
# command to run tests
script:
  - pytest --cov=pyshb
